# Generated by Django 2.1.5 on 2019-01-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duespayment',
            name='dues_type',
            field=models.CharField(choices=[('NEWQ1', 'New member - Jan to Dec'), ('NEWQ2', 'New member - Apr to Dec'), ('NEWQ3', 'New member - Jul to Dec'), ('NEWQ4', 'New member - Oct to Dec'), ('RENEW', 'Renewal - Jan to Dec')], max_length=5),
        ),
    ]
