# Generated by Django 2.1.5 on 2019-01-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20190129_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
