# Generated by Django 2.1.5 on 2019-04-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190202_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(blank=True, choices=[('MEETING', 'Meeting'), ('TESTING', 'Testing Session'), ('SOCIAL', 'Social Event'), ('OTHER', 'Other Event')], max_length=10),
        ),
    ]
