# Generated by Django 2.1.5 on 2019-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20190331_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingplace',
            name='address',
            field=models.CharField(blank=True, max_length=95),
        ),
        migrations.AlterField(
            model_name='meetingplace',
            name='city',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='meetingplace',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='meetingplace',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
