# Generated by Django 2.1.5 on 2019-04-29 03:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20190423_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
