# Generated by Django 2.1.5 on 2019-04-29 08:08

import datetime
import pytz
from django.db import migrations, models

home_tz = pytz.timezone("Pacific/Honolulu")

class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20190428_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=home_tz.localize(datetime.datetime(2019, 12, 31))),
            preserve_default=False,
        ),
    ]
