# Generated by Django 2.1.5 on 2019-05-01 07:16

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_announcement_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('entry', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
