# Generated by Django 2.1.5 on 2019-05-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20190430_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbookentry',
            options={'verbose_name_plural': 'Logbook entries'},
        ),
    ]
