# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('N', 'New Member'), ('R', 'Renewal'), ('U', 'Update Info')], max_length=1, verbose_name='Application type')),
                ('callsign', models.CharField(max_length=6)),
                ('license_type', models.CharField(choices=[('T', 'Technician'), ('G', 'General'), ('A', 'Advanced'), ('E', 'Extra')], max_length=1)),
                ('expiration_date', models.DateField(verbose_name='My license expires')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=95)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('mailing_list', models.BooleanField(verbose_name='Add me to the club mailing list')),
                ('wd_online', models.BooleanField(verbose_name='I would like to read the Wireless Dispatch online')),
                ('arrl_member', models.BooleanField(verbose_name='I am an ARRL member')),
                ('need_new_badge', models.BooleanField(verbose_name='I need a new membership badge')),
            ],
        ),
    ]
