# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-27 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0002_auto_20180526_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2018, 5, 26), verbose_name='My license expires'),
        ),
    ]
