# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-27 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0003_auto_20180526_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 6, 53, 40, 267645, tzinfo=utc), verbose_name='My license expires'),
        ),
    ]
