# Generated by Django 2.0.5 on 2018-06-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0008_remove_member_app_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('dues_type', models.CharField(choices=[('N', 'New member'), ('R', 'Renewal')], max_length=1)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHK', 'Check'), ('PP', 'PayPal')], max_length=4)),
                ('ref_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_members.Member')),
            ],
        ),
    ]
