# Generated by Django 2.0.5 on 2018-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0009_duespayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='duespayment',
            name='membership_year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
