# Generated by Django 2.0.5 on 2018-06-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0010_duespayment_membership_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duespayment',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
