# Generated by Django 2.1.5 on 2019-01-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0013_member_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duespayment',
            name='member',
        ),
        migrations.DeleteModel(
            name='DuesPayment',
        ),
    ]
