# Generated by Django 2.1.5 on 2019-01-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0014_auto_20190121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(blank=True, verbose_name='My license expires'),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_type',
            field=models.CharField(blank=True, choices=[('T', 'Technician'), ('G', 'General'), ('A', 'Advanced'), ('E', 'Amateur Extra')], max_length=1),
        ),
    ]
