# Generated by Django 2.1.5 on 2019-02-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0015_auto_20190129_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
