# Generated by Django 2.1.5 on 2019-05-12 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_members', '0017_auto_20190508_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='arrl_member',
            field=models.BooleanField(default=False, verbose_name='I am an ARRL member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='callsign',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(regex='^([A-Z0-9]{1,2})(\\d)([A-Z]{1,3})$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='mailing_list',
            field=models.BooleanField(default=True, verbose_name='Add me to the club mailing list'),
        ),
        migrations.AlterField(
            model_name='member',
            name='need_new_badge',
            field=models.BooleanField(default=False, verbose_name='I need a new membership badge'),
        ),
        migrations.AlterField(
            model_name='member',
            name='wd_online',
            field=models.BooleanField(default=True, verbose_name='I would like to read the Wireless Dispatch online'),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{5}(\\-\\d{4})?')]),
        ),
    ]
